name: Build website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci # --production
    - run: npm run build --if-present

    - run: sed '/scripts.html/d' .gitignore > temp && mv temp .gitignore
    - run: sed '/dist/d' .gitignore > temp && mv temp .gitignore

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: .
