name: Build wtfsystems website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build site
      run: npm ci # --production
      run: npm run build --if-present

    - name: Gitignore modifications
    # Remove output files from .gitignore
      run: sed '/scripts.html/d' .gitignore > temp && mv temp .gitignore
      run: sed '/dist/d' .gitignore > temp && mv temp .gitignore
    # Add additional items to .gitignore
      run: echo 'src/' >> .gitignore
      run: echo '.babelrc' >> .gitignore
      run: echo '.eslintignore' >> .gitignore
      run: echo '.eslintrc.js' >> .gitignore
      run: echo 'LICENSE' >> .gitignore
      run: echo 'LICENSE.md' >> .gitignore
      run: echo 'README.md' >> .gitignore
      run: echo 'package-lock.json' >> .gitignore
      run: echo 'package.json' >> .gitignore
      run: echo 'webpack.config.babel.js' >> .gitignore

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: .
